name: MJ Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: my-metrics-0.svg
          output_action: pull-request
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Hongkong
      - uses: lowlighter/metrics@latest
        with:
          filename: my-metrics-1.svg
          output_action: pull-request-merge
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Hongkong

