name: MJ Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          output_action: pull-request-merge
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Hongkong
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_skyline: yes
          plugin_skyline_year: 2023
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1

      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: my-metrics-0.svg
      #     output_action: pull-request
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     config_timezone: Hongkong
